//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartId { get; set; }
        public int UserId { get; set; }
        public int MovieId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual User User { get; set; }
        public virtual Movy Movy { get; set; }
    }
}
